leftnav:
- identifier: 8f0a8ee4-7455-0b1d-3aa0-9222b014ca8a
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-ea5f06258cb74de7aa112e7e7bfc68d5
  name: I. Electronic Materials and Devices
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITX+3.15.1x+2T2017/about
  weight: 1000
- identifier: external-5bda60ef39ca4e50bf86043d9fb81d18
  name: II. Optical Materials and Devices
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.15.2x+2T2017/about
  weight: 1010
- identifier: external-bd4f5c25ae5a46779762ac2765002334
  name: III. Magnetic Materials and Devices
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.15.3x+2T2017/about
  weight: 1020
