leftnav:
- identifier: 8f0a8ee4-7455-0b1d-3aa0-9222b014ca8a
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-969621830e5d401ea75a600f562eedef
  name: I. Electronic Materials and Devices
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITX+3.15.1x+2T2017/about
  weight: 1000
- identifier: external-5e032f59ff594663bc26e91b207606aa
  name: II. Optical Materials and Devices
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.15.2x+2T2017/about
  weight: 1010
- identifier: external-a3cd635672e3444696f7b08c526f1247
  name: III. Magnetic Materials and Devices
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+3.15.3x+2T2017/about
  weight: 1020
